// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package repository

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9478868cDecodeGithubComCymiamMetircsStoreInternalRepository(in *jlexer.Lexer, out *MemStorage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "gauges":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Gauges = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 float64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = float64(in.Float64())
					}
					(out.Gauges)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "counters":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Counters = make(map[string][]int64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 []int64
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						in.Delim('[')
						if v2 == nil {
							if !in.IsDelim(']') {
								v2 = make([]int64, 0, 8)
							} else {
								v2 = []int64{}
							}
						} else {
							v2 = (v2)[:0]
						}
						for !in.IsDelim(']') {
							var v3 int64
							if in.IsNull() {
								in.Skip()
							} else {
								v3 = int64(in.Int64())
							}
							v2 = append(v2, v3)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Counters)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9478868cEncodeGithubComCymiamMetircsStoreInternalRepository(out *jwriter.Writer, in MemStorage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"gauges\":"
		out.RawString(prefix[1:])
		if in.Gauges == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Gauges {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				out.Float64(float64(v4Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"counters\":"
		out.RawString(prefix)
		if in.Counters == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.Counters {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				if v5Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v6, v7 := range v5Value {
						if v6 > 0 {
							out.RawByte(',')
						}
						out.Int64(int64(v7))
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MemStorage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9478868cEncodeGithubComCymiamMetircsStoreInternalRepository(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MemStorage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9478868cEncodeGithubComCymiamMetircsStoreInternalRepository(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MemStorage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9478868cDecodeGithubComCymiamMetircsStoreInternalRepository(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MemStorage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9478868cDecodeGithubComCymiamMetircsStoreInternalRepository(l, v)
}
