// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package repository

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson9478868cDecodeGithubComCymiamMetricsStoreInternalRepository(in *jlexer.Lexer, out *MemStorage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "gauges":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Gauges = make(map[string]float64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 float64
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = float64(in.Float64())
					}
					(out.Gauges)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "counters":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Counters = make(map[string]int64)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 int64
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = int64(in.Int64())
					}
					(out.Counters)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson9478868cEncodeGithubComCymiamMetricsStoreInternalRepository(out *jwriter.Writer, in MemStorage) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"gauges\":"
		out.RawString(prefix[1:])
		if in.Gauges == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v3First := true
			for v3Name, v3Value := range in.Gauges {
				if v3First {
					v3First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v3Name))
				out.RawByte(':')
				out.Float64(float64(v3Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"counters\":"
		out.RawString(prefix)
		if in.Counters == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Counters {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				out.Int64(int64(v4Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v MemStorage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson9478868cEncodeGithubComCymiamMetricsStoreInternalRepository(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v MemStorage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson9478868cEncodeGithubComCymiamMetricsStoreInternalRepository(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *MemStorage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson9478868cDecodeGithubComCymiamMetricsStoreInternalRepository(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *MemStorage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson9478868cDecodeGithubComCymiamMetricsStoreInternalRepository(l, v)
}
